#!/bin/bash

# Create user directory and set permissions
groupadd $SFTPGROUP && \
     #useradd -G $SFTPGROUP -s /sbin/nologin $USERNAME && \
    useradd -G $SFTPGROUP $USERNAME && \
    mkdir -p "/home/$USERNAME" && \
    chown root "/home/$USERNAME" && \
    chmod g+rx "/home/$USERNAME" && \
    mkdir "/home/$USERNAME/sftpdir" && \
    mkdir "/home/$USERNAME/sftpdir/tmp" && \
    chown $USERNAME:$USERNAME "/home/$USERNAME/sftpdir/tmp"

# Setup authorized keys
mkdir "/home/$USERNAME/.ssh" && \
    chown $USERNAME:$USERNAME "/home/$USERNAME/.ssh" && \
    chmod 700 "/home/$USERNAME/.ssh" && \
    touch "/home/$USERNAME/.ssh/authorized_keys" && \
    echo $PUBLIC_KEY >> "/home/$USERNAME/.ssh/authorized_keys"

# GCSFuse Mount
mkdir "/home/$USERNAME/sftpdir/gcs" && \
    chown "$USERNAME:$USERNAME" "/home/$USERNAME/sftpdir/gcs"

su -c "gcsfuse $BUCKET_NAME /home/$USERNAME/sftpdir/gcs" "$USERNAME"

# If PASSWORD env variable is empty, then disable password auth
if [ "$PASSWORD" != "" ]
then
    echo "$USERNAME:$PASSWORD" | chpasswd && \
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
fi

exec /usr/sbin/sshd -D -e
